# Generated by Django 5.2.7 on 2026-04-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_usersubscription"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_c4e471_idx",
            old_name="notificatio_user_id_445f01_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_611c58_idx",
            old_name="notificatio_user_id_ee8947_idx",
        ),
        migrations.RenameIndex(
            model_name="usersubscription",
            new_name="user_subscr_plan_42d7a9_idx",
            old_name="user_subscr_plan_9152e7_idx",
        ),
    ]
