# Generated by Django 5.2.7 on 2026-04-15 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerpaymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='offer.offer'),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed the application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_requests', to='offer.influencerpaymentmethod'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='influencerpaymentmethod',
            index=models.Index(fields=['user', 'is_primary'], name='offer_influ_user_id_fe2879_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerpaymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='offer_influ_user_id_4bb514_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapplication',
            index=models.Index(fields=['status', '-submitted_at'], name='offer_offer_status_6d46c8_idx'),
        ),
        migrations.AddIndex(
            model_name='offerapplication',
            index=models.Index(fields=['offer', 'status'], name='offer_offer_offer_i_13bc56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerapplication',
            unique_together={('offer', 'user')},
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['user', 'status'], name='offer_payou_user_id_c0ee20_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['-requested_at'], name='offer_payou_request_52f3bc_idx'),
        ),
    ]
