# Generated by Django 5.2.7 on 2026-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_alter_offerapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offerapplication",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offerapplication",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="offerapplication",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Unpaid", "Unpaid"),
                    ("InEscrow", "In Escrow"),
                    ("Released", "Released"),
                    ("Refunded", "Refunded"),
                ],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="offerapplication",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offerapplication",
            name="released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
