# Generated by Django 5.2.7 on 2026-04-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_savedoffer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='savedoffer',
            table='offer_savedoffer',
        ),
    ]
