# Generated by Django 5.2.7 on 2026-04-06 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0003_offerapplication_paid_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluencerPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("PayPal", "PayPal"),
                            ("BankTransfer", "Bank Transfer"),
                        ],
                        default="PayPal",
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("details", models.CharField(max_length=255)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Paid", "Paid"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payout_requests",
                        to="offer.influencerpaymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.AddIndex(
            model_name="influencerpaymentmethod",
            index=models.Index(
                fields=["user", "is_primary"], name="offer_influ_user_id_fe2879_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="influencerpaymentmethod",
            index=models.Index(
                fields=["user", "is_active"], name="offer_influ_user_id_4bb514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutrequest",
            index=models.Index(
                fields=["user", "status"], name="offer_payou_user_id_c0ee20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payoutrequest",
            index=models.Index(
                fields=["-requested_at"], name="offer_payou_request_52f3bc_idx"
            ),
        ),
    ]
