"""
Django settings for influBridge project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-80b8e^7edo53%)(bfzj6m&)1fv8hku(c+91nuq8c903&os7hy$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Parse ALLOWED_HOSTS from environment variable
allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_str:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]
else:
    # Default for development
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Add Render domain automatically if RENDER env var is present
if os.getenv('RENDER'):
    ALLOWED_HOSTS.append(os.getenv('RENDER_EXTERNAL_HOSTNAME', ''))

# Add Google Cloud Run domain
ALLOWED_HOSTS.extend([
    'influBridge-251801873872.us-central1.run.app',
    '.run.app',  # Allow all Cloud Run domains
    '.a.run.app'  # Alternative Cloud Run domain
])

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = []
csrf_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_str.split(',') if origin.strip()]
elif os.getenv('RENDER'):
    # Add Render domain automatically
    render_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME')
    if render_hostname:
        CSRF_TRUSTED_ORIGINS.append(f"https://{render_hostname}")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #external apps
    'rest_framework',
    'graphene_django',
    'django_extensions',
    'django_filters',
    'schema_graph',
    'corsheaders',
    'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    #internal apps
    'users',
    'category',
    'offer',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True 
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'influBridge.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'influBridge.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Check if DATABASE_URL is provided (Neon PostgreSQL connection string)
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Use DATABASE_URL if provided (recommended for Neon/production)
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL, 
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Fallback to SQLite for local development only
    # WARNING: SQLite won't work on Vercel (read-only filesystem)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (use cloud storage like S3 for production)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'graphql_jwt.backends.JSONWebTokenBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# GraphQL
GRAPHENE = {
    'SCHEMA': 'influBridge.schema.schema',
    'SCHEMA_INDENT': 4,
    'MIDDLEWARE': [
        'users.middleware.NormalizeAuthorizationHeaderMiddleware',
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}

# GraphQL JWT Settings
from datetime import timedelta

GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=60),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=7),
    'JWT_COOKIE_SECURE': not DEBUG,
    'JWT_COOKIE_DOMAIN': None,
    'JWT_COOKIE_SAMESITE': 'Lax',
    'JWT_PAYLOAD_HANDLER': 'users.utils.jwt_payload_handler',  # Custom payload with name, email, role
}


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cookies',
]

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'api': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Email Configuration
# For development: set DEBUG_EMAIL=True to print emails to console instead of SMTP
# For production: provide valid SMTP credentials (Gmail, SendGrid, Office365, etc.)

DEBUG_EMAIL = os.getenv('DEBUG_EMAIL', 'False') == 'True'

if DEBUG_EMAIL and DEBUG:
    # Development mode: print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = 587
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'dev@example.com')
    EMAIL_HOST_PASSWORD = 'console-backend'
    EMAIL_USE_TLS = True
else:
    # Production mode: use SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'your-email@gmail.com')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'your-app-password')
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Account verification toggle.
# Set to False to let users sign up and log in without the 6-digit email step.
EMAIL_VERIFICATION_REQUIRED = os.getenv('EMAIL_VERIFICATION_REQUIRED', 'False') == 'True'

# Frontend URL for email verification links
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# Stripe payment settings
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_CURRENCY = os.getenv('STRIPE_CURRENCY', 'usd').lower()
# Local dev helper: bypass Stripe checkout/webhooks and simulate successful payment.
STRIPE_SIMULATION_MODE = os.getenv('STRIPE_SIMULATION_MODE', 'False') == 'True'

# Stripe recurring prices for platform subscriptions.
STRIPE_PRICE_COMPANY_PLUS = os.getenv('STRIPE_PRICE_COMPANY_PLUS', '')
STRIPE_PRICE_COMPANY_PRO = os.getenv('STRIPE_PRICE_COMPANY_PRO', '')
STRIPE_PRICE_INFLUENCER_PLUS = os.getenv('STRIPE_PRICE_INFLUENCER_PLUS', '')
STRIPE_PRICE_INFLUENCER_PRO = os.getenv('STRIPE_PRICE_INFLUENCER_PRO', '')

# Usage limits. Set a value <= 0 for unlimited.
COMPANY_FREE_CAMPAIGNS_PER_MONTH = int(os.getenv('COMPANY_FREE_CAMPAIGNS_PER_MONTH', '3'))
COMPANY_PLUS_CAMPAIGNS_PER_MONTH = int(os.getenv('COMPANY_PLUS_CAMPAIGNS_PER_MONTH', '30'))
COMPANY_PRO_CAMPAIGNS_PER_MONTH = int(os.getenv('COMPANY_PRO_CAMPAIGNS_PER_MONTH', '0'))

INFLUENCER_FREE_APPLICATIONS_PER_WEEK = int(os.getenv('INFLUENCER_FREE_APPLICATIONS_PER_WEEK', '5'))
INFLUENCER_PLUS_APPLICATIONS_PER_WEEK = int(os.getenv('INFLUENCER_PLUS_APPLICATIONS_PER_WEEK', '40'))
INFLUENCER_PRO_APPLICATIONS_PER_WEEK = int(os.getenv('INFLUENCER_PRO_APPLICATIONS_PER_WEEK', '0'))
